security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
            App\Entity\User:
                algorithm: bcrypt

    providers:
        in_memory: { memory: ~ }
        db_provider:
                    entity:
                        class: App\Entity\User
                        property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            provider: db_provider

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

            form_login:
                    # submit the login form here
                    check_path: /login_check

                    # the user is redirected here when they need to log in
                    login_path: /login

                    # if true, forward the user to the login form instead of redirecting
                    use_forward: false

                    # login success redirecting options (read further below)
                    always_use_default_target_path: false
                    default_target_path:            /user
                    target_path_parameter:          _target_path
                    use_referer:                    false

                    # login failure redirecting options (read further below)
#                    failure_path:    /foo
#                    failure_forward: false
#                    failure_path_parameter: _failure_path
#                    failure_handler: some.service.id
#                    success_handler: some.service.id

                    # field names for the username and password fields
                    username_parameter: login[login]
                    password_parameter: login[password]

                    # by default, the login form *must* be a POST, not a GET
                    post_only:      true
                    remember_me:    true

            remember_me:
                  secret:   '%kernel.secret%'
                  lifetime: 604800 # 1 week in seconds
                  path:     /
                  remember_me_parameter: remember_me

            logout:
                    path: /logout
                    target: /

            anonymous: ~

    access_control:
        - { path: ^/user, roles: ROLE_USER}
        - { path: ^/admin, roles: ROLE_ADMIN}
